title: "Mofart Ayiega"
description: "PhD student in Linguistics at Michigan State University. Research in Bantu morphosyntax, morphosemantics and variation (Swahili & Other Bantu languages)."
theme: minima
url: "https://mofartayiega.github.io"
baseurl: ""
header_pages:
  - index.md
  - about.md
  - publications.md
  - teaching.md
  - cv.md
author: "Mofart Ayiega"
email: "ayiegamo@msu.edu"
github_username: "MofartAyiega"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

